apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: excalidraw
  namespace: excalidraw
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "ExcaliDraw"
    gethomepage.dev/description: "Self-hosted Excalidraw dashboard"
    gethomepage.dev/icon: "excalidraw.png"
    gethomepage.dev/group: "Applications"
    gethomepage.dev/weight: "25"
spec:
  rules:
    - host: excalidraw.ganam.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: excalidraw-frontend
                port:
                  number: 80
