apiVersion: v1
kind: Service
metadata:
  name: excalidraw-frontend
  namespace: excalidraw
  labels:
    app: excalidraw-frontend
    dns.service-controller.io/enabled: "true"
    dns.service-controller.io/hostname: "excalidraw.buildin.group"
    exposure.service-controller.io/type: "internal"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: excalidraw-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: excalidraw-backend
  namespace: excalidraw
  labels:
    app: excalidraw-backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: excalidraw-backend
