apiVersion: v1
kind: Service
metadata:
  name: tududi
  namespace: tududi
  labels:
    app: tududi
    dns.service-controller.io/enabled: "true"
    dns.service-controller.io/hostname: "tududi.buildin.group"
    exposure.service-controller.io/type: "internal"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3002
      protocol: TCP
  selector:
    app: tududi
