apiVersion: v1
kind: Service
metadata:
  name: kitchenowl
  namespace: kitchenowl
  labels:
    app: kitchenowl
    dns.service-controller.io/enabled: "true"
    dns.service-controller.io/hostname: "kitchenowl.buildin.group"
    exposure.service-controller.io/type: "internal"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: kitchenowl
