apiVersion: v1
kind: Service
metadata:
  name: kan
  namespace: kan
  labels:
    app: kan
    dns.service-controller.io/enabled: "true"
    dns.service-controller.io/hostname: "kan.buildin.group"
    exposure.service-controller.io/type: "internal"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: kan