apiVersion: v1
kind: Service
metadata:
  name: obsidian-livesync
  namespace: obsidian-livesync
  labels:
    app: obsidian-livesync
    dns.service-controller.io/enabled: "true"
    dns.service-controller.io/hostname: "obsidian-livesync.buildin.group"
    exposure.service-controller.io/type: "internal"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 5984
      protocol: TCP
  selector:
    app: obsidian-livesync
