# INTERNAL Service - accessible via ingress
# This service will be accessible via internal DNS using MetalLB IP + Ingress
apiVersion: v1
kind: Service
metadata:
  name: papra
  namespace: papra
  labels:
    app: papra
    # DNS Management Labels for Internal Service
    dns.service-controller.io/enabled: "true"
    dns.service-controller.io/hostname: "papra.ganam.app"
    exposure.service-controller.io/type: "internal"
spec:
  type: ClusterIP # Use ClusterIP for internal services with ingress
  ports:
    - name: http
      port: 80
      targetPort: 1221
      protocol: TCP
  selector:
    app: papra
